defaults: &defaults
  host: localhost
  allow_dynamic_fields: false
  raise_not_found_error: false
  identity_map_enabled: true
  
development:
  <<: *defaults
  database: spark_development

test:
  <<: *defaults
  database: spark_test

# set these environment variables on your prod server
production:
  <<: *defaults
  host: localhost
  # username: eleven_spark
  # password: spark_junhuangyi
  database: spark_eleven_1584
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
