sina_weibo:
  client_id: 13450026
  client_secret: 29f6df4ae62fa587264dc2799a484f45
  register_url: "xiwangbang.com"
  redirect_uri: http://xiwangbang.com/login?platform=SinaWeibo

tencent_weibo:
  client_id: 801067714
  client_secret: 42ad1d6476e3b16e6fce4af9afceadaa
  register_url: xiwangbang.com
  redirect_uri: http://xiwangbang.com/login?platform=TencentWeibo